[build]
  publish = "portfolio/"
  command = "echo 'No build command'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "echo 'No local dev command'"
  port = 8888
  publish = "portfolio/"
